title: TITAN SQUAD
description: A turn-based superhero battle game.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
mac_url: https://drive.google.com/open?id=17Y0mC5pm5XpwCHhFFPgHnsiQmBR1rWxo
android_url: https://drive.google.com/open?id=1dAGlGwZuB9c-qw3UrbsvpRdoOPwGGQDe
windows_url: https://drive.google.com/open?id=17wf6lkcRjkyyXzSxEF0QQD-RNizqdWuY
github_url: https://github.com/titansquad
